export const USER_LOGIN_REQUEST = "LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "LOGIN_FAIL";

export const USER_LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "LOGOUT_FAIL";

export const CREATE_CLASS_REQUEST = "CREATE_CLASS_REQUEST";
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const CREATE_CLASS_FAIL = "CREATE_CLASS_FAIL";

export const FETCH_CLASS_REQUEST = "FETCH_CLASS_REQUEST";
export const FETCH_CLASS_SUCCESS = "FETCH_CLASS_SUCCESS";
export const FETCH_CLASS_FAIL = "FETCH_CLASS_FAIL";

export const JOIN_CLASS_REQUEST = "JOIN_CLASS_REQUEST";
export const JOIN_CLASS_SUCCESS = "JOIN_CLASS_SUCCESS";
export const JOIN_CLASS_FAIL = "JOIN_CLASS_FAIL";

export const FETCH_ASSIGNMENTS_REQUEST = "FETCH_ASSIGNMENTS_REQUEST";
export const FETCH_ASSIGNMENTS_SUCCESS = "FETCH_ASSIGNMENTS_SUCCESS";
export const FETCH_ASSIGNMENTS_FAIL = "FETCH_ASSIGNMENTS_FAIL";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const CREATE_QUIZ_REQUEST = "CREATE_QUIZ_REQUEST";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAIL = "CREATE_QUIZ_FAIL";

export const FETCH_CLASS_DETAILS_REQUEST = "FETCH_CLASS_DETAILS_REQUEST";
export const FETCH_CLASS_DETAILS_SUCCESS = "FETCH_CLASS_DETAILS_SUCCESS";
export const FETCH_CLASS_DETAILS_FAIL = "FETCH_CLASS_DETAILS_FAIL";

export const FETCH_QUIZ_REQUEST = "FETCH_QUIZ_REQUEST";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";
export const FETCH_QUIZ_FAIL = "FETCH_QUIZ_FAIL";

export const SUBMIT_QUIZ_REQUEST = "SUBMIT_QUIZ_REQUEST";
export const SUBMIT_QUIZ_SUCCESS = "SUBMIT_QUIZ_SUCCESS";
export const SUBMIT_QUIZ_FAIL = "SUBMIT_QUIZ_FAIL";

export const FETCH_QUIZ_SUBMISSIONS_REQUEST = "FETCH_QUIZ_SUBMISSIONS_REQUEST";
export const FETCH_QUIZ_SUBMISSIONS_SUCCESS = "FETCH_QUIZ_SUBMISSIONS_SUCCESS";
export const FETCH_QUIZ_SUBMISSIONS_FAIL = "FETCH_QUIZ_SUBMISSIONS_FAIL";

export const FETCH_PENDING_TASKS_REQUEST = "FETCH_PENDING_TASKS_REQUEST";
export const FETCH_PENDING_TASKS_SUCCESS = "FETCH_PENDING_TASKS_SUCCESS";
export const FETCH_PENDING_TASKS_FAIL = "FETCH_PENDING_TASKS_FAIL";

export const FETCH_ASSIGNMENT_SUBMISSIONS_REQUEST =
  "FETCH_ASSIGNMENT_SUBMISSIONS_REQUEST";
export const FETCH_ASSIGNMENT_SUBMISSIONS_SUCCESS =
  "FETCH_ASSIGNMENT_SUBMISSIONS_SUCCESS";
export const FETCH_ASSIGNMENT_SUBMISSIONS_FAIL =
  "FETCH_ASSIGNMENT_SUBMISSIONS_FAIL";

export const FETCH_USERS_QUIZ_SUBMISSION_REQUEST =
  "FETCH_USERS_QUIZ_SUBMISSION_REQUEST";
export const FETCH_USERS_QUIZ_SUBMISSION_SUCCESS =
  "FETCH_USERS_QUIZ_SUBMISSION_SUCCESS";
export const FETCH_USERS_QUIZ_SUBMISSION_FAIL =
  "FETCH_USERS_QUIZ_SUBMISSION_FAIL";

export const FETCH_USERS_ASSIGNMENT_SUBMISSION_REQUEST =
  "FETCH_USERS_ASSIGNMENT_SUBMISSION_REQUEST";
export const FETCH_USERS_ASSIGNMENT_SUBMISSION_SUCCESS =
  "FETCH_USERS_ASSIGNMENT_SUBMISSION_SUCCESS";
export const FETCH_USERS_ASSIGNMENT_SUBMISSION_FAIL =
  "FETCH_USERS_ASSIGNMENT_SUBMISSION_FAIL";

export const CREATE_ASSIGNMENT_REQUEST = "CREATE_ASSIGNMENT_REQUEST";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";
export const CREATE_ASSIGNMENT_FAIL = "CREATE_ASSIGNMENT_FAIL";

export const FETCH_ASSIGNMENT_REQUEST = "FETCH_ASSIGNMENT_REQUEST";
export const FETCH_ASSIGNMENT_SUCCESS = "FETCH_ASSIGNMENT_SUCCESS";
export const FETCH_ASSIGNMENT_FAIL = "FETCH_ASSIGNMENT_FAIL";

export const CREATE_ASSIGNMENT_SUBMISSION_REQUEST =
  "CREATE_ASSIGNMENT_SUBMISSION_REQUEST";
export const CREATE_ASSIGNMENT_SUBMISSION_SUCCESS =
  "CREATE_ASSIGNMENT_SUBMISSION_SUCCESS";
export const CREATE_ASSIGNMENT_SUBMISSION_FAIL =
  "CREATE_ASSIGNMENT_SUBMISSION_FAIL";

export const DOWNLOAD_ASSIGNMENT_REQUEST = "DOWNLOAD_ASSIGNMENT_REQUEST";
export const DOWNLOAD_ASSIGNMENT_SUCCESS = "DOWNLOAD_ASSIGNMENT_SUCCESS";
export const DOWNLOAD_ASSIGNMENT_FAIL = "DOWNLOAD_ASSIGNMENT_FAIL";

export const DOWNLOAD_ASSIGNMENT_SUBMISSION_REQUEST =
  "DOWNLOAD_ASSIGNMENT_SUBMISSION_REQUEST";
export const DOWNLOAD_ASSIGNMENT_SUBMISSION_SUCCESS =
  "DOWNLOAD_ASSIGNMENT_SUBMISSION_SUCCESS";
export const DOWNLOAD_ASSIGNMENT_SUBMISSION_FAIL =
  "DOWNLOAD_ASSIGNMENT_SUBMISSION_FAIL";

export const USER_VIDEO_REQUEST = "USER_VIDEO_REQUEST";
export const USER_VIDEO_SUCCESS = "USER_VIDEO_SUCCESS";
export const USER_VIDEO_FAIL = "USER_VIDEO_FAIL";

export const FETCH_ANNOUNCEMENTS_REQUEST = "FETCH_ANNOUNCEMENTS_REQUEST";
export const FETCH_ANNOUNCEMENTS_SUCCESS = "FETCH_ANNOUNCEMENTS_SUCCESS";
export const FETCH_ANNOUNCEMENTS_FAIL = "FETCH_ANNOUNCEMENTS_FAIL";

export const CREATE_ANNOUNCEMENT_REQUEST = "CREATE_ANNOUNCEMENT_REQUEST";
export const CREATE_ANNOUNCEMENT_SUCCESS = "CREATE_ANNOUNCEMENT_SUCCESS";
export const CREATE_ANNOUNCEMENT_FAIL = "CREATE_ANNOUNCEMENT_FAIL";

export const DELETE_ANNOUNCEMENT_REQUEST = "DELETE_ANNOUNCEMENT_REQUEST";
export const DELETE_ANNOUNCEMENT_SUCCESS = "DELETE_ANNOUNCEMENT_SUCCESS";
export const DELETE_ANNOUNCEMENT_FAIL = "DELETE_ANNOUNCEMENT_FAIL";

export const GRADE_ASSIGNMENT_REQUEST = "GRADE_ASSIGNMENT_REQUEST";
export const GRADE_ASSIGNMENT_SUCCESS = "GRADE_ASSIGNMENT_SUCCESS";
export const GRADE_ASSIGNMENT_FAIL = "GRADE_ASSIGNMENT_FAIL";
