export const USER_LOGIN_REQUEST = "LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "LOGIN_FAIL";

export const CREATE_CLASS_REQUEST = "CREATE_CLASS_REQUEST";
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const CREATE_CLASS_FAIL = "CREATE_CLASS_FAIL";

export const FETCH_CLASS_REQUEST = "FETCH_CLASS_REQUEST";
export const FETCH_CLASS_SUCCESS = "FETCH_CLASS_SUCCESS";
export const FETCH_CLASS_FAIL = "FETCH_CLASS_FAIL";

export const JOIN_CLASS_REQUEST = "JOIN_CLASS_REQUEST";
export const JOIN_CLASS_SUCCESS = "JOIN_CLASS_SUCCESS";
export const JOIN_CLASS_FAIL = "JOIN_CLASS_FAIL";

export const ADD_QUESTION = "ADD_QUESTION";
