export const USER_LOGIN_REQUEST = "LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "LOGIN_FAIL";

export const CREATE_CLASS_REQUEST = "CREATE_CLASS_REQUEST";
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const CREATE_CLASS_FAIL = "CREATE_CLASS_FAIL";

export const FETCH_CLASS_REQUEST = "FETCH_CLASS_REQUEST";
export const FETCH_CLASS_SUCCESS = "FETCH_CLASS_SUCCESS";
export const FETCH_CLASS_FAIL = "FETCH_CLASS_FAIL";

export const JOIN_CLASS_REQUEST = "JOIN_CLASS_REQUEST";
export const JOIN_CLASS_SUCCESS = "JOIN_CLASS_SUCCESS";
export const JOIN_CLASS_FAIL = "JOIN_CLASS_FAIL";

export const ADD_QUESTION = "ADD_QUESTION";

export const FETCH_ASSIGNMENTS_REQUEST = "FETCH_ASSIGNMENTS_REQUEST";
export const FETCH_ASSIGNMENTS_SUCCESS = "FETCH_ASSIGNMENTS_SUCCESS";
export const FETCH_ASSIGNMENTS_FAIL = "FETCH_ASSIGNMENTS_FAIL";

export const CREATE_QUIZ_REQUEST = "CREATE_QUIZ_REQUEST";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAIL = "CREATE_QUIZ_FAIL";

export const FETCH_CLASS_DETAILS_REQUEST = "FETCH_CLASS_DETAILS_REQUEST";
export const FETCH_CLASS_DETAILS_SUCCESS = "FETCH_CLASS_DETAILS_SUCCESS";
export const FETCH_CLASS_DETAILS_FAIL = "FETCH_CLASS_DETAILS_FAIL";

export const FETCH_QUIZ_REQUEST = "FETCH_QUIZ_REQUEST";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";
export const FETCH_QUIZ_FAIL = "FETCH_QUIZ_FAIL";

export const SUBMIT_QUIZ_REQUEST = "SUBMIT_QUIZ_REQUEST";
export const SUBMIT_QUIZ_SUCCESS = "SUBMIT_QUIZ_SUCCESS";
export const SUBMIT_QUIZ_FAIL = "SUBMIT_QUIZ_FAIL";

export const FETCH_SUBMISSIONS_REQUEST = "FETCH_SUBMISSIONS_REQUEST";
export const FETCH_SUBMISSIONS_SUCCESS = "FETCH_SUBMISSIONS_SUCCESS";
export const FETCH_SUBMISSIONS_FAIL = "FETCH_SUBMISSIONS_FAIL";

export const FETCH_USERS_QUIZ_SUBMISSION_REQUEST =
  "FETCH_USERS_QUIZ_SUBMISSION_REQUEST";
export const FETCH_USERS_QUIZ_SUBMISSION_SUCCESS =
  "FETCH_USERS_QUIZ_SUBMISSION_SUCCESS";
export const FETCH_USERS_QUIZ_SUBMISSION_FAIL =
  "FETCH_USERS_QUIZ_SUBMISSION_FAIL";

export const CREATE_ASSIGNMENT_REQUEST = "CREATE_ASSIGNMENT_REQUEST";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";
export const CREATE_ASSIGNMENT_FAIL = "CREATE_ASSIGNMENT_FAIL";

export const FETCH_ASSIGNMENT_REQUEST = "FETCH_ASSIGNMENT_REQUEST";
export const FETCH_ASSIGNMENT_SUCCESS = "FETCH_ASSIGNMENT_SUCCESS";
export const FETCH_ASSIGNMENT_FAIL = "FETCH_ASSIGNMENT_FAIL";

export const CREATE_ASSIGNMENT_SUBMISSION_REQUEST =
  "CREATE_ASSIGNMENT_SUBMISSION_REQUEST";
export const CREATE_ASSIGNMENT_SUBMISSION_SUCCESS =
  "CREATE_ASSIGNMENT_SUBMISSION_SUCCESS";
export const CREATE_ASSIGNMENT_SUBMISSION_FAIL =
  "CREATE_ASSIGNMENT_SUBMISSION_FAIL";

export const DOWNLOAD_ASSIGNMENT_REQUEST = "DOWNLOAD_ASSIGNMENT_REQUEST";
export const DOWNLOAD_ASSIGNMENT_SUCCESS = "DOWNLOAD_ASSIGNMENT_SUCCESS";
export const DOWNLOAD_ASSIGNMENT_FAIL = "DOWNLOAD_ASSIGNMENT_FAIL";

export const DOWNLOAD_ASSIGNMENT_SUBMISSION_REQUEST =
  "DOWNLOAD_ASSIGNMENT_SUBMISSION_REQUEST";
export const DOWNLOAD_ASSIGNMENT_SUBMISSION_SUCCESS =
  "DOWNLOAD_ASSIGNMENT_SUBMISSION_SUCCESS";
export const DOWNLOAD_ASSIGNMENT_SUBMISSION_FAIL =
  "DOWNLOAD_ASSIGNMENT_SUBMISSION_FAIL";
